### PR TITLE
New metrics

### PR DESCRIPTION
**Pull request by mbarouski**

### CODE REVIEW

**Comment by leprechau** [comment]
Triggering Travis build ...

**Comment by leprechau** [comment]
@maximka777 Thank you for the PR.  Would you mind re-basing this on the current master so we can validate the new Travis tests?

**Comment by leprechau** [comment]
Also, please see #476 ... is this duplicative?

**Comment by maximka777** [comment]
> Also, please see #476 ... is this duplicative?

@leprechau 

This PR is a kinda continuation of Frank's work in #476.

If changes in this PR are useful for the project I can rebase, fix tests and do necessary changes.
But this PR is open for ~1 year. Let me please know if it is still relevant?

Thanks!

**Comment by leprechau** [comment]
@maximka777 I know there is still interest around updating the metrics.  Frank has left the project and handed it over to myself and team for maintenance (see #735) for background.

If you have the time I'd like to see a rebased and updated version of your work that includes changes frank made since you started this PR (if any) and current changes to master.

**Comment by maximka777** [comment]
@leprechau I will be trying to do this asap.
Some code review would be nice to get coz I am not a very experienced Go developer.

**Comment by vilva42** [comment]
@maximka777 do you have any plans of adding this feature?

**Comment by maximka777** [comment]
@vilva42 sorry, I'm not sure that I have enough time for this next few months.
If you think these changes are required by people then you could look at them and do some refactoring and testing? :thinking:

**Pull request closed without merging**
