### PR TITLE
Add GoReleaser workflow.

### PR DESCRIPTION
**Pull request by tristanmorgan**
I theory this should create draft releases whenever we push a tag. tested on another project tristanmorgan/packer-plugin-terraform but I don't sign releases there.

### CODE REVIEW

**Comment by tristanmorgan** [comment]
In Theory this should work.... 
https://github.com/tristanmorgan/fabio/actions/runs/11945328443/job/33297812068
except I got an "exec format error" during the docker build phase.

**Comment by tristanmorgan** [comment]
Much better now. https://github.com/tristanmorgan/fabio/actions/runs/12021638796/job/33512478338
just needs docker creds before merge.

**Comment by tristanmorgan** [comment]
End to end release complete.

https://github.com/tristanmorgan/fabio/actions/runs/12024248733/job/33519865884

https://github.com/tristanmorgan/fabio/releases/tag/v1.6.4-test
 and 
 https://hub.docker.com/layers/fabiolb/fabio/1.6.4-test/images/sha256-2ccd5aa333e45256b5a80aaa7008409a638802e139ea82ffa2619151034d9f7d?context=repo

**Comment by tristanmorgan** [comment]
P.S. requires secrets called DOCKERHUB_TOKEN, GPG_PRIVATE_KEY, GPG_PASSPHRASE and a variable called DOCKERHUB_USERNAME.

**Review by aaronhurt — APPROVED** [review]
nice work :)

**Pull request merged**
