### PR TITLE
Now setting the X-Forwarded-Host header if not present. Add matching …

### PR DESCRIPTION
**Pull request by LeReverandNox**
…unit tests.

Hi @magiconair, 
I needed to have the X-Forwarded-Host header for many of my services,  so here it is :)
Let me know if there's wrong with it.

Thanks !
LeReverandNox

### CODE REVIEW

**Comment by commarla** [comment]
Hey can we have a feedback on this one? 

Thanks!

**Comment by magiconair** [comment]
Hi @LeReverandNox and @commarla, thanks for both the PR and the nudge. The last couple of weeks were a bit more stressful than expected. I've merged the PR and added some subsequent commits to clean it up (integration test, ordering, simplifying). Nothing major. 

Thanks again!

Frank

**Comment by commarla** [comment]
Thanks to you @magiconair

**Comment by LeReverandNox** [comment]
Thanks a lot @magiconair ! We owe you one :)

**Pull request merged**
