### PR TITLE
compare host using lowercase

### PR DESCRIPTION
**Pull request by shantanugadgil**
use lowercase comparison for host lookup #542

### CODE REVIEW

**Comment by shantanugadgil** [comment]
@leprechau my Go skills are pretty basic and I had suggested this change as it worked for me.
(I have tested the binary for my use case)

I am perfectly fine with any other changes as well.
Should I resubmit with the other changes?

**Comment by leprechau** [comment]
I think we can make all lookups and adds lowercase by making two simple changes in `route/table.go` like this ...

```diff
diff --git a/route/table.go b/route/table.go
index bb689dc..1646e74 100644
--- a/route/table.go
+++ b/route/table.go
@@ -136,6 +136,7 @@ func NewTable(s string) (t Table, err error) {
 // addRoute adds a new route prefix -> target for the given service.
 func (t Table) addRoute(d *RouteDef) error {
        host, path := hostpath(d.Src)
+       host = strings.ToLower(host) // maintain compatibility with parseURLPrefixTag
 
        if d.Src == "" {
                return errInvalidPrefix
@@ -383,6 +384,7 @@ func (t Table) LookupHost(host string, pick picker) *Target {
 }
 
 func (t Table) lookup(host, path, trace string, pick picker, match matcher) *Target {
+       host = strings.ToLower(host) // routes are always added lowercase
        for _, r := range t[host] {
                if match(path, r) {
                        n := len(r.Targets)
```

**Comment by leprechau** [comment]
Running a `make test` those two changes to `table.go` don't appear to break existing tests.

**Comment by leprechau** [comment]
@shantanugadgil Thank you!

**Comment by shantanugadgil** [comment]
hehe @leprechau thank _you_ !!! 👍

**Pull request merged**
