### PR TITLE
update github.com/hashicorp/consul/api to v1.4.0

### PR DESCRIPTION
**Pull request by andyroyle**

### CODE REVIEW

**Comment by leprechau** [comment]
Could you update the go modules with the proper semantic versioning tag and ensure it matches the vendor in sources?

See here for more information with working with the new go modules system: https://github.com/golang/go/wiki/Modules

**Comment by magiconair** [comment]
Can you do this via ’GO111MODULE=on go mod edit -require ...’ and then ’go mod vendor’ please?

Need to update the docs

**Comment by andyroyle** [comment]
My first time using go modules, sorry

**Comment by leprechau** [comment]
@andyroyle this is also needed for #517 and #566 ... do you have the time to update it to use v1.4.0 as a module or would you like me to close it?

**Comment by magiconair** [comment]
LGTM

**Comment by andyroyle** [comment]
Cheers!

**Comment by andyroyle** [comment]
Not at all, I just wanted the updated consul client :+1:

**Pull request closed without merging**
