### PR TITLE
Updating tcp dynamic proxy to match on routes that are port only

### LINKED ISSUE #797: TCP Dynamic Proxy route without specifying exact IP?
I'm using tcp-dynamic proxy with `proxy.addr = :9999,0.0.0.0:0;proto=tcp-dynamic;refresh=5s` but wondering if there's a way to use routes without hardcoding an IP address if I understand correctly?

For example, I have a service with the following tags:

```
fabio-0.0.0.0:6379 proto=tcp
fabio-:6379 proto=tcp
fabio-mydnsrecord:6379 proto=tcp
```

The routes get added successfully, but they all result in "No route found" logs.

```
Oct 30 18:07:52 default-ubuntu-1804 fabio[19887]: 2020/10/30 18:07:52 [WARN] No route for 192.168.33.33:6379
```

Is it possible to be able to resolve a hostname instead of use an IP address, or route based on port-only instead of ip:port?

Thanks in advance!

### PR DESCRIPTION
**Pull request by nathanejohnson**
This fixes #797

### CODE REVIEW

**Comment by nathanejohnson** [comment]
@murphymj25 could you take a look at this?

Thanks!

**Comment by murphymj25** [comment]
@nathanejohnson It's been a while since I've looked at this code, but based tcp_proxy.go what you have looks correct.

**Comment by killerdejavu** [comment]
@nathanejohnson Would be great to have this PR merged! 😄

**Comment by leprechau** [comment]
LGTM, and thanks @murphymj25 for the confirmation.

**Pull request merged**
