### PR TITLE
Refactor metrics

### LINKED ISSUE #126: Riemann metrics support
Will you accept PRs adding support for new metric targets (new go-metric modules)? It's not really clear to me what the implications of that are for you as a maintainer.

### LINKED ISSUE #165: Support dogstatd with tags
Will Fabio eventually support (or does it already?) tagging statsd metrics? This is key when using Datadog.

### LINKED ISSUE #211: Support for prometheus
Hi there,

it would be great to get the fabio metrics also to a prometheus instance. 
Is there any chance for ?

greetz

Equilibri0

### LINKED ISSUE #253: Add support for influxdb metrics
Will you  adding support for new metric targets  [influxdb](https://github.com/influxdata/influxdb)?

### LINKED ISSUE #326: Send metrics to cloudwatch
It would be great to be able to have a plugin that sends metrics to AWS cloudwatch per endpoint

### LINKED ISSUE #327: Statsd output is not good
Aside from the actual broken protocol packets in #207 the implementation of instrumentation with statsd in this project is just really bad. Exporting gauges of pre-aggregated metrics is a serious anti-pattern to typical/normal statsd instrumentation best practices. I'm curious if there is some specific reason why this model was adopted. Is there any appetite for re-instrumenting in a more standard manner?

### LINKED ISSUE #371: [Question] Stats - Status code per service
Hi,

I send all stats to a statsD instance, but im missing one nifty stat - http status code count per service.
You provide a global count of HTTP status codes, but I would like to e.g. see 404 for a given service.

### PR DESCRIPTION
**Pull request by magiconair**
This patch refactors the metrics support within fabio to
achieve several goals:

 * support labels for DogstatD, Prometheus and others
 * support raw events for statsd and others without aggregation
 * support multiple backends simultaneously to support migration
 * make integration of new metrics backends and/or libraries simple
 * being fully backwards compatible to not break existing setups

One of the main challenges is that fabio generates names for the metrics
targets through templates and that these templates are configurable. A
metrics backend which supports labels needs to generate a different name
for the same metric than one that does not support labels.

Combining this with the need to support multiple different metrics
backends at runtime means that none of the existing metrics libraries
like go-kit/metrics and hashicorp/go-metrics is a good fit. However,
they can be used as drivers which reduces the need for testing and makes
integration of new backends simpler since fabio does not need to rely on
a single metrics library.

This patch is work in progress with the new metrics code in the metrics4
package and the old metrics code in the 'metrics_old' package where it
is kept for reference until it has been migrated or removed. The basic
architecture should be good enough to add more providers and
functionality so that the community can help.

Right now there are two providers "flat" and "label" to demonstrate the
concepts. They provide counter and timers in statsd/dogstatd format and
can be configured with -metrics.target=flat[,label]. Other providers
should be added in the same way.

The metrics_old code should be converted to the new provider scheme.

The go-kit/metrics library currently supports most of the necessary
drivers and is the preferred way of integrating new drivers.

The list below is a probably incomplete list of things that need to be
done:

 * The configuration is not used except for metrics.target
 * The drivers from the metrics_old package need to be migrated
 * Additional drivers from go-kit need to be added
 * The old rcrowley/go-metrics code relies on 'registries' for
   namespacing. After the routing table has changed the registry needs
   to be pruned of services which no longer exist so that go-metrics
   stops reporting them.
 * The RX/TX counters in the TCP and TCP+SNI proxy are probably
   sub-optimal or broken.
 * Some counters may not have been initialized properly, e.g. WSConn
 * WSConn should probably be a gauge which also needs to be set to 0 on
   startup.
 * The approach of injecting a noop metrics provider if none has been
   set has already bitten me once since some metrics are reported while
   others are not. I need to think about this a bit more.

Fixes #126
Fixes #165
Fixes #211
Fixes #253
Fixes #326
Fixes #327
Fixes #371
Closes #329
Closes #331
Closes #334
Closes #335

### CODE REVIEW

**Comment by magiconair** [comment]
As for approach please see https://github.com/fabiolb/fabio/issues/211#issuecomment-375880738

**Comment by magiconair** [comment]
Lets first try to add one go-kit/metrics driver to verify the approach and then we can spread the work to support more.

**Comment by magiconair** [comment]
To test this I'm currently doing this:

```
# terminal 1
consul agent -dev

# terminal 2
cd $GOPATH/src/github.com/fabiolb/fabio/demo/server
go build
./server -prefix /foo

# terminal 3
cd $GOPATH/src/github.com/fabiolb/fabio
go build && ./fabio -metrics.target=flat,label

# terminal 4
curl -i localhost:9999/foo
```

**Comment by magiconair** [comment]
I'm wondering whether https://opencensus.io/go.html might be a better foundation. Does someone have some experience with this?

**Comment by nir0s** [comment]
This is getting old. Literally :)

**Comment by chenjpu** [comment]
+1

**Comment by magiconair** [comment]
Yeah, I know. I was switching jobs and moving my family to a different country. Lots of changes, new language and all. Also, fabio needs a bigger community of contributors since I have become a bottleneck. I am starting to catch my breath again and get some energy on working on fabio again. However, this project is now way more than what I've ever needed to build. As much as I like programming I'll never be able to keep up with the demand by myself. 

The metrics code is still bugging me and I'd like to solve this properly but I could really use some help here. If someone wants to work with me on this we could finally tick this one off.

**Comment by ketzacoatl** [comment]
Maintaining a project like this can be such an under-appreciated, and often times thankless investment, so thanks for letting us know what you've got going on and what help you need. Good luck on the move and all the transitions that has with it.

As far as getting metrics incorporated.. I won't be much help with go, but I would be happy to make myself available for testing metrics in an updated fabio. It'd be most easy for me to test with prometheus, but I can help with others too.

**Comment by blalor** [comment]
@magiconair what help do you need to get this branch where you're comfortable with merging it?

**Comment by leprechau** [comment]
@blalor @ketzacoatl Frank has handed maintenance of the project over to myself and others here at ENA.  I'd love to continue the work here on metrics if either of you are available for testing and/or code contribution.

**Comment by ketzacoatl** [comment]
I'd be more than happy to help with testing. I'd be limited in golang, but happy to participate in pushing this one thru!

**Comment by leprechau** [comment]
@ketzacoatl Thank you.  I've gotten a response from @maximka777 in #586 ... if he's interested in taking up the torch we will definitely need independent testing.

**Comment by nathanejohnson** [comment]
I'm planning to pick this back up.  I just squashed Frank's commits and rebased off master, it builds and tests pass.  I'm going to see if I can at least get a prometheus and statsd integration going with go-kit

**Comment by nathanejohnson** [comment]
so I have pushed a pretty major update here.  Currently all previously supported backends have been implemented, though there will definitely be changes required for users of statsd and likely graphite as well.  the statsd implementation was rather broken - counters never reset which is a violation of how counters are supposed to work in statsd. Graphite changed because the new implementation is based off the go-kit graphite adapter for their metrics framework.  The main changes are around histograms, since they use a different backend package.  This is unfortunate, however this gets us to the positives: namely, tag support for backends that can support them, and a way forward for backends that don't support tags.

Prometheus has been added, in order to use it you need to configure a listener with proto=prometheus .  this lets you configure it like any other listeners, with TLS support or not, with ACLs etc.

I would love some testers, and assuming people can suffer through the graphite / statsd pains changes, I'd like to get this slated for a 1.6 release sometime in the not too distant future.

I would really appreciate some help in testing the stats backends.  This is still very much a work in progress

**Comment by ketzacoatl** [comment]
Thank you for all your work on this @nathanejohnson!

> I would love some testers, and assuming people can suffer through the graphite / statsd pains changes, I'd like to get this slated for a 1.6 release sometime in the not too distant future.
> 
> I would really appreciate some help in testing the stats backends. This is still very much a work in progress

Should we build the branch from source to test, or is there a build artifact somewhere we should pull or use?

I haven't been running the statsd backend, but I would be happy to test that out now (with datadog).

**Comment by nathanejohnson** [comment]
@ketzacoatl so I just pushed a new change to this branch that should support tagging with dogstatsd.  I don't have an artifact just now that you can get to easily, but if you just checkout the metrics4 branch and issue a make build that should get you a working binary.  If you'd like something prebuilt that's fine too, let me know GOOS / GOARCH and I can put something up somewhere for you to grab.  It would be nice to do a beta release, but I'm not sure yet the best way to do it without cluttering up the releases page on github.

**Comment by ketzacoatl** [comment]
> I don't have an artifact just now that you can get to easily, but if you just checkout the metrics4 branch and issue a make build that should get you a working binary. If you'd like something prebuilt that's fine too, let me know GOOS / GOARCH and I can put something up somewhere for you to grab.

I don't have a golang env setup (though I have set it up in the past), so if you could build one for linux/amd64, that would be grand. I can figure it out if that's not easy to do.

> It would be nice to do a beta release, but I'm not sure yet the best way to do it without cluttering up the releases page on github.

Maybe a RC can be released?

**Comment by nathanejohnson** [comment]
[fabio_v1.5.15-7-ge2c0310.tar.gz](https://github.com/fabiolb/fabio/files/5656090/fabio_v1.5.15-7-ge2c0310.tar.gz)

**Comment by nathanejohnson** [comment]
@ketzacoatl and anyone else interested, this is a tarball with mac and linux builds, as well as a signed manifest.

**Comment by nathanejohnson** [comment]
https://drive.google.com/drive/folders/1lMsA1Q3PFi_xXOvV-ZUNR9GPI4EVFXv8

This is going to be a "private" beta for now, though anyone with the link can download the files.  I did darwin and linux in amd64, I can add others if there is interest.

**Comment by ketzacoatl** [comment]
Sorry, I've been busy. This on my todo list though.

**Pull request merged**
