### PR TITLE
Add HTTP/2 support for gRPC

### LINKED ISSUE #244: distributed tracing system
Is it possible to plug some distributed tracing system (like Zipkin) directly to fabio (like for Linkerd) ?
If not how it is better to implement this ?

### PR DESCRIPTION
**Pull request by magiconair**
Fixes #244

### CODE REVIEW

**Comment by james-xiang** [comment]
Hi magiconair,
I am currently evaluating fabio with gRPC load balancing support.  I could figure it out how the routing table works for the gRPC endpoints. Is this feature ready or when it will be added ?
Thanks a lot.

**Comment by phedoreanu** [comment]
Hi @magiconair , I'm trying to get this PR to work, but one of your repos is private?
```
init failed: unable to solve the dependency graph: Solving failure: no valid source could be created:
	failed to set up sources from the following URLs:
https://github.com/magiconair/go-metrics-statsd
: remote repository at https://github.com/magiconair/go-metrics-statsd does not exist, or is inaccessible: ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
: exit status 128
```

Can you please make it public? Or remove it as a dependency altogether?

Thanks!

**Comment by magiconair** [comment]
I thought I did. Can you rebase?

—
Frank Schröder

**Comment by phedoreanu** [comment]
Sure, but it's still private.

```
$curl -D-  https://github.com/magiconair/go-metrics-statsd                                                             HTTP/1.1 404 Not Found
Server: GitHub.com
Date: Wed, 11 Apr 2018 12:52:53 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
```

**Comment by magiconair** [comment]
The library is in the vendor folder. Why do you need to pull it?

You should not need to pull any libraries at all.

-- Frank @Amsterdam

**Comment by magiconair** [comment]
I don't, so please don't. 

-- Frank @Amsterdam

**Comment by magiconair** [comment]
Please use govendor and vendorfmt. 

-- Frank @Amsterdam

**Comment by phedoreanu** [comment]
Do you have a good reason why?

**Comment by magiconair** [comment]
Because it works and there is no upside on using dep. I want to have the code self-contained to avoid exactly the question you're asking.

-- Frank @Amsterdam

**Comment by phedoreanu** [comment]
I'm sorry, but I don't agree with you.
> `dep` is the official experiment, but not yet the official tool.

And it has 3.63x the number of contributors than `govendor`. 149 (`dep`) vs 41 (`govendor`).

Also last `dep` commit was 5 days ago, as opposed to `govendor` which was on the 9th of Feb.

**Comment by magiconair** [comment]
That's fine and please feel free to use `dep` for your projects if you think it is a better fit. But allow me the same courtesy and accept the choices I've made.

**Comment by phedoreanu** [comment]
Of course, feel free to decline the PR with `dep`, but at least be open to new proposals.

Already by running `dep init` it highlighted the problem that one dependency (`go-metrics-statsd`) isn't available (like all the others are), but it's **manually hardcoded** inside `vendor/`.

**Comment by magiconair** [comment]
That is the very purpose of the `vendor` folder so that you do not have to rely on external repositories. :)

Please do me the favor and submit your PR according to the requirements of this project. 

Feel free to submit another PR where you switch the dependency control to another tool but at this point I will not merge this since I don't want to rely on external dependencies for building fabio.

**Comment by phedoreanu** [comment]
How are you not dependent on external dependencies?! 😆 
```
$ cat vendor/vendor.json
{"path":"github.com/armon/go-proxyproto","checksumSHA1":"eAall4ACaMG40mzSJ5Oc95GiF1A=","revision":"609d6338d3a76ec26ac3fe7045a164d9a58436e7","revisionTime":"2015-02-06T18:58:55-08:00"},
{"path":"github.com/circonus-labs/circonus-gometrics","checksumSHA1":"ZAdLZ0e/hin4AXxdS9F8y0yi/bg=","revision":"f8c68ed96a065c10344dcaf802f608781fc0a981","revisionTime":"2016-08-30T16:47:25Z"},
...
{"path":"github.com/cyberdelia/go-metrics-graphite","checksumSHA1":"8/Q1JbAHUmL4sDURLq6yron4K/I=","revision":"b8345b7f01d571b05366d5791a034d872f1bb36f","revisionTime":"2015-08-25T20:22:00-07:00"},
{"path":"github.com/fatih/structs","checksumSHA1":"zKLQNNEpgfrJOwVrDDyBMYEIx/w=","revision":"5ada2f449b108d87dbd8c1e60c32cdd065c27886","revisionTime":"2016-06-01T09:31:17Z"},
{"path":"github.com/gobwas/glob","checksumSHA1":"/RE0VzeaXdaBUNeNMUXWqzly7qY=","revision":"19c076cdf202b3d1c0489bdfa2f2f289f634474b","revisionTime":"2018-02-08T21:18:42Z"},
...
{"path":"github.com/hashicorp/consul/api","checksumSHA1":"GsJ84gKbQno8KbojhVTgSVWNues=","revision":"402636ff2db998edef392ac6d59210d2170b3ebf","revisionTime":"2017-04-05T04:22:14Z","version":"v0.8.0","versionExact":"v0.8.0"},
{"path":"github.com/hashicorp/errwrap","checksumSHA1":"cdOCt0Yb+hdErz8NAQqayxPmRsY=","revision":"7554cd9344cec97297fa6649b055a8c98c2a1e55","revisionTime":"2014-10-27T22:47:10-07:00"},
{"path":"github.com/hashicorp/go-cleanhttp","checksumSHA1":"Uzyon2091lmwacNsl1hCytjhHtg=","revision":"ad28ea4487f05916463e2423a55166280e8254b5","revisionTime":"2016-04-07T17:41:26Z"},
...
{"path":"github.com/hashicorp/vault/api","checksumSHA1":"9/RHDTjqflfK3/f2Tfvwx+82I40=","revision":"f627c01df8d7bebb403cf899ca1beb24f5fc84cd","revisionTime":"2016-06-14T07:51:08Z","version":"v0.6.0","versionExact":"v0.6.0"},
{"path":"github.com/magiconair/go-metrics-statsd","checksumSHA1":"1I3MjrGSOw5rPtlrHcGI8bJfLyA=","revision":"380638b554e36fe109711b41e09917d94b235e86","revisionTime":"2017-01-25T16:17:32Z"},
...
{"path":"github.com/mitchellh/go-homedir","checksumSHA1":"AXacfEchaUqT5RGmPmMXsOWRhv8=","revision":"1111e456ffea841564ac0fa5f69c26ef44dafec9","revisionTime":"2016-06-06T03:01:22Z"},
...
{"path":"github.com/pascaldekloe/goe/verify","checksumSHA1":"4tr8yNUt5DB8GXc5y+uq6J7TJ54=","revision":"f99183613f483cd9b8c79359d572836e243e0763","revisionTime":"2015-07-19T21:56:08+02:00"},
{"path":"github.com/pkg/profile","checksumSHA1":"C3yiSMdTQxSY3xqKJzMV9T+KnIc=","revision":"5b67d428864e92711fcbd2f8629456121a56d91f","revisionTime":"2017-05-09T09:25:25Z"},
{"path":"github.com/rcrowley/go-metrics","checksumSHA1":"ODTWX4h8f+DW3oWZFT0yTmfHzdg=","revision":"3e5e593311103d49927c8d2b0fd93ccdfe4a525c","revisionTime":"2015-07-19T09:56:14-07:00"},
{"path":"github.com/rogpeppe/fastuuid","checksumSHA1":"ehRkDJisGCCSYdNgyvs1gSywSPE=","revision":"6724a57986aff9bff1a1770e9347036def7c89f6","revisionTime":"2015-01-06T09:31:45Z"},
{"path":"github.com/sergi/go-diff/diffmatchpatch","checksumSHA1":"iWCtyR1TkJ22Bi/ygzfKDvOQdQY=","revision":"24e2351369ec4949b2ed0dc5c477afdd4c4034e8","revisionTime":"2017-01-18T13:12:30Z"},
{"path":"golang.org/x/net/http2","checksumSHA1":"N1akwAdrHVfPPrsFOhG2ouP21VA=","revision":"f2499483f923065a842d38eb4c7f1927e6fc6e6d","revisionTime":"2017-01-14T04:22:49Z"},
{"path":"golang.org/x/net/http2/hpack","checksumSHA1":"HzuGD7AwgC0p1az1WAQnEFnEk98=","revision":"f2499483f923065a842d38eb4c7f1927e6fc6e6d","revisionTime":"2017-01-14T04:22:49Z"},
{"path":"golang.org/x/net/idna","checksumSHA1":"GIGmSrYACByf5JDIP9ByBZksY80=","revision":"f2499483f923065a842d38eb4c7f1927e6fc6e6d","revisionTime":"2017-01-14T04:22:49Z"},
{"path":"golang.org/x/net/lex/httplex","checksumSHA1":"3xyuaSNmClqG4YWC7g0isQIbUTc=","revision":"f2499483f923065a842d38eb4c7f1927e6fc6e6d","revisionTime":"2017-01-14T04:22:49Z"},
{"path":"golang.org/x/net/websocket","checksumSHA1":"xvuVB+aMh4udpinGsmtK31pcWC0=","revision":"9946ad7d5eae91d8edca4f54d1a1e130a052e823","revisionTime":"2015-10-20T22:50:55Z"},
{"path":"golang.org/x/sync/singleflight","checksumSHA1":"VhUZFUuhLFSBFUfskMC4am5RIdc=","revision":"8e0aa688b654ef28caa72506fa5ec8dba9fc7690","revisionTime":"2017-07-19T03:38:01Z"}
...
```

**Comment by magiconair** [comment]
Because they are all forked and checked into the main source repository. You have to check out one and only one git repository. Again, that is the purpose of the `vendor` folder - but I think you know this.

Look I don't want to be a jerk and I would appreciate your contribution on this issue. I also think you know exactly what my motivation is and what I am trying to tell you. I have asked you to respect my choices and I've explained why changing this tooling is not interesting for me. 

If this is a unacceptable choice for you then I accept that. However, I would like to ask you to stop arguing about this now since we're only going in circles. 

Please make a choice to either pick this up or not but do not waste other peoples time to submit code that someone else has to clean up just because you feel like it.

**Comment by magiconair** [comment]
I'm closing this in favor of #575. Please let me know if this is a mistake.

**Pull request closed without merging**
