### PR TITLE
Fix various minor things

### PR DESCRIPTION
**Pull request by antham**

### CODE REVIEW

**Comment by antham** [comment]
@magiconair What about this PR ?

**Comment by magiconair** [comment]
Hi @antham, the last couple of weeks were a bit more stressful than expected. This LGTM. Merging and thanks for fixing! :)

**Comment by antham** [comment]
Maybe you could add the -s flag to gofmt in your Makefile, it's what I ran.

**Comment by magiconair** [comment]
@antham Good idea. Done in 119bd53.

**Pull request merged**
