### PR TITLE
Issue 554 Added compiled glob matching using LRU Cache

### PR DESCRIPTION
**Pull request by galen0624**
#554 

New PR replacing old one #555

### CODE REVIEW

**Comment by leprechau** [comment]
@galen0624 Thank you for the PR.  It looks like other merges have created conflicts.  Would you mind resolving those so we can get this merged and improve the performance of the glob matcher?

Thank you again.

**Comment by galen0624** [comment]
@leprechau  I'll see what I can do this week or early next.

**Comment by galen0624** [comment]
@leprechau OK this one I believe should be OK now.

**Comment by leprechau** [comment]
Thank you!

**Pull request merged**
