### PR TITLE
Added compiled glob matching using LRU cache

### PR DESCRIPTION
**Pull request by galen0624**
#554  Review for CPU usage of Mutex.

### CODE REVIEW

**Comment by galen0624** [comment]
#554 The use of sync.Map increased the performance from 3500 TPS to 6500 TPS.  
The glob_cache_test file needs refactoring as you have to use sync.Map.Range and there is no ability to get the len of a sync.Map currently

**Comment by galen0624** [comment]
#554 Updated glob_cache to support all types that implement the glob.Glob Interfaces.  Make test now passes all checks.

**Comment by galen0624** [comment]
#554  Updated to remove type switch and assert type to glob.Glob interface.

**Comment by magiconair** [comment]
This looks OK. If you rebase this then we can merge this as well. I assume you're using that in production as well?

**Comment by galen0624** [comment]
We are not using this in prod.  We don't use GLOB matching.  That being said we have tested it.  -- https://github.com/fabiolb/fabio/issues/554#issuecomment-425276410

I will rebase line and PR.

**Comment by galen0624** [comment]
rebased this PR.

**Comment by galen0624** [comment]
Closing and recreating with new PR #615

**Pull request closed without merging**
