### PR TITLE
ignore fabio.exe

### PR DESCRIPTION
**Pull request by leprechau**
add fabio.exe to the `.gitignore` and remove from the source tree

### CODE REVIEW

**Comment by kostyrev** [comment]
Hi! I'd like to point out that though you've removed binary from the tree the binary is still there in history
```
$ git rev-list --all --objects | sed -n $(git rev-list --objects --all | cut -f1 -d' ' | git cat-file --batch-check | grep blob | sort -n -k 3 | tail -n1 | while read hash type size; do echo -n "-e s/$hash/$size/p "; done) | sort -n -k1
12059648 fabio.exe
```
and cloning this repo still takes 14M of space
```
$ du -s -h ../fabio/
14M	../fabio/
```

**Comment by magiconair** [comment]
@kostyrev Thanks for reminding me.

However, the 14M is not just the `.git` directory but also the `vendor` folder, the `docs` and the rest of the code. The savings don't seem worth a force push to `master`.

```
$ git clone git@github.com:fabiolb/fabio fabio.clean
$ cd fabio.clean/
$ du -hs ../fabio.clean
 14M	../fabio.clean
$ du -hs .git
  8.7M	.git
$ git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch fabio.exe" HEAD
$ rm -rf .git/refs/original/ && git reflog expire --all &&  git gc --aggressive --prune=now
$ du -hs .git
7.2M	.git
$ du -hs ../fabio.clean/
 13M	../fabio.clean/
```

**Comment by magiconair** [comment]
FWIW, running `git gc` trimmed my `.git` directory down from `20M` to `8.1M`

**Comment by kostyrev** [comment]
FYI: I used steps from [github guide](https://help.github.com/articles/removing-sensitive-data-from-a-repository/#using-filter-branch) and get those results
```
$ du -sh ../fabio.clean
8.9M	../fabio.clean
$ du -sh ../fabio.master
14M	../fabio.master
```

**Pull request merged**
