### PR TITLE
Issue 558 concurrent service updates

### PR DESCRIPTION
**Pull request by galen0624**
#558

### CODE REVIEW

**Comment by magiconair** [comment]
Hi @galen0624, thanks for the patch! After looking at it I thought that this was an excellent opportunity to finally refactor the service monitor code for Consul and also add some tests for the route generation code. I hope that is OK with you?

I've also taken a slightly different approach for the concurrent fetching by limiting the number of concurrent go routines running. 

It would be awesome if you could test #564 and see whether it has the desired effect.

One thing I've noticed is that the current code also looks up the datacenter for every service. Moving this out of the code should already save some cycles but generally that is a cheap call.

I am curious on why you a) created a custom http client for the consul client and b) why you limited the number of idle connections. Could you elaborate on this?

**Comment by magiconair** [comment]
I'll close this in the meantime.

**Comment by magiconair** [comment]
#564 supersedes this.

**Comment by magiconair** [comment]
Hmm, should this then be in the common code? Does it hurt?

**Comment by galen0624** [comment]
No it shouldn't.  I apologize I neglected to remove it before the PR.

**Comment by magiconair** [comment]
No need to apologize. :)

**Comment by galen0624** [comment]
@magiconair  OK I tested the update and it behaved as expected.  I observed a 5-10% CPU increase using `registry.consul.serviceMonitors = 100` on an 8 Core box.  Memory was not impacted that I could tell.   

 I was also thinking about the issue with the custom http.Transport.  If the consul backend is consistent (meaning same URL/Host) the TIME_WAIT issue will still be something to solve regardless if Fabio is talking to localhost or a remote consul.  The `MaxIdleConnsPerHost` is per host.  During out testing today I observed around 25K TIME_WAIT connections with roughly 2000 services. 

 Below is somewhat of an explanation on the settings.  

http://tleyden.github.io/blog/2016/11/21/tuning-the-go-http-client-library-for-load-testing/

**Comment by galen0624** [comment]
With 2000 + services there is always changes.  The Consul blocking query is irrelevant in our ENV because of that.   I instituted a configurable query timer in the "Shim" instead.  It acts like a blocking query to Fabio.  The expectation is that route updates in Fabio happen within the query timer interval.  Without concurrent service updates each Fabio was taking 20+ seconds to run through all of the services.   Additionally we have sized our Consul ENV to support the amount of queries that we are sending from the FabioShims.  

I'll continue testinging with various `registry.consul.serviceMonitors` and see where it breaks down.

**Comment by galen0624** [comment]
After testing it seems that `registry.consul.serviceMonitors = 16` is the sweet spot for meeting our current query interval.

**Comment by galen0624** [comment]
Also I have updated and tested your issue-558 branch with the new custom http.Transport if you want me to PR it back.

**Comment by leprechau** [comment]
To the earlier point of the number of Fabio instances and service monitors and the potential load on Consul ... would it make sense to incorporate the ability to use the new agent cache added upstream in v1.3.0?

**Comment by leprechau** [comment]
Maybe make an available global tunable to set a cache interval for the health calls?  I could introduce a separate PR for that specifically.

**Comment by magiconair** [comment]
I was thinking the same thing. Either wait for changes or poll. I think this would go nice with the refactoring. I could add @galen0624 as contributor so that we can work on the same branch instead of merging small bits back and forth.

**Comment by magiconair** [comment]
Just did. @galen0624 do you have a GPG key to sign your commits? I should update the contrib guidelines with that.

**Comment by magiconair** [comment]
If not, here is a good guide on how to create a good set of keys: https://github.com/drduh/YubiKey-Guide

**Comment by magiconair** [comment]
#564 is on the `issue-558` branch

**Comment by galen0624** [comment]
I have one through KeyBase.  Will that work?  If not I'll get another one setup tonight.

**Comment by galen0624** [comment]
@leprechau Can you elaborate on the V1.3.0?  Is that Consul?  

Are you talking about the Agent Cache described below for /catalog/service/my-serivce

https://www.consul.io/api/catalog.html

**Comment by galen0624** [comment]
@magiconair @leprechau I stared the updates for polling intervals.  Not 100% complete yet but a starting point.  I'm not sure if you want me to submit a PR or commit to the issue-558 branch?  The code can be found here for now.

https://github.com/galen0624/fabio/tree/issue-558

**Comment by magiconair** [comment]
@galen0624 I've left some comments on https://github.com/galen0624/fabio/commit/474d896768c761d68ce60142fafaea6703eb9616. 

Any objection on merging #564?

**Comment by galen0624** [comment]
@magiconair No objections on Merging #564.  We have been using it in production for the last few weeks.  I will be updating the other request and submitting an update based on your feedback.

**Comment by galen0624** [comment]
I will.

**Pull request closed without merging**
